[tox]
envlist = py311
skipsdist = true

[testenv]
deps = -r requirements-dev.txt
setenv =
    PYTHONPATH = {toxinidir}
commands =
    pytest tests/ -v --cov=appian_parser --cov-report=term-missing --cov-report=xml:coverage.xml

[testenv:lint]
deps = -r requirements-dev.txt
setenv =
    PYTHONPATH = {toxinidir}
commands =
    flake8 appian_parser --max-line-length=120 --ignore=E203,W503,W293,W291,F401,F841,E128,E722,E501,W504,W292,E302,F811
